In [3]:
import numpy as np
import csv

In [51]:
# открытие файла data.csv как матрицы numpy
my_data = np.genfromtxt("data.csv", delimiter=',')
print(my_data)

[[ 88. 126. 102. ... 255. 186. 233.]
 [139.  93.  64. ... 232. 114. 147.]
 [295. 265. 123. ...  89.  13. 104.]
 ...
 [ 96.  69. 180. ...  57.  49.  55.]
 [108.  72. 229. ...  65. 102. 160.]
 [ 93. 133.  39. ... 258.  26. 175.]]


In [52]:
# количество измерений
print(my_data.ndim)

2


In [53]:
# размерность матрицы
print(my_data.shape)

(50, 50)


In [54]:
# количество элементов
print(my_data.size)

2500


In [71]:
# тип элементов
print(my_data.dtype)

float64


In [56]:
# первый элемент первой строки
print(my_data[0,0])

88.0


In [72]:
# последняя строка
print(my_data[-1:,:])

[[93.00000000 133.00000000 39.00000000 287.00000000 154.00000000
  299.00000000 220.00000000 212.00000000 118.00000000 123.00000000
  217.00000000 215.00000000 266.00000000 267.00000000 241.00000000
  38.00000000 15.00000000 104.00000000 164.00000000 138.00000000
  60.00000000 186.00000000 63.00000000 146.00000000 265.00000000
  286.00000000 255.00000000 24.00000000 240.00000000 127.00000000
  28.00000000 28.00000000 173.00000000 259.00000000 33.00000000
  261.00000000 130.00000000 12.00000000 55.00000000 163.00000000
  95.00000000 35.00000000 276.00000000 76.00000000 267.00000000
  193.00000000 91.00000000 258.00000000 26.00000000 175.00000000]]


In [74]:
# каждый 5 элемент последней строки
print(my_data[-1:, ::5])

[[93.00000000 299.00000000 217.00000000 38.00000000 60.00000000
  286.00000000 28.00000000 261.00000000 95.00000000 193.00000000]]


In [70]:
# вывод 6 первых строк
print(my_data[:6, :])

[[0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000]
 [139.00000000 93.00000000 64.00000000 28.00000000 162.00000000
  102.00000000]
 [295.00000000 265.00000000 123.00000000 99.00000000 256.00000000
  210.00000000]
 [2.00000000 140.00000000 288.00000000 45.00000000 108.00000000
  263.00000000]
 [165.00000000 79.00000000 132.00000000 58.00000000 147.00000000
  172.00000000]
 [196.00000000 132.00000000 284.00000000 26.00000000 113.00000000
  148.00000000]
 [225.00000000 13.00000000 266.00000000 158.00000000 158.00000000
  18.00000000]
 [277.00000000 163.00000000 90.00000000 245.00000000 130.00000000
  210.00000000]
 [58.00000000 223.00000000 142.00000000 275.00000000 65.00000000
  129.00000000]
 [192.00000000 44.00000000 292.00000000 53.00000000 111.00000000
  114.00000000]
 [182.00000000 290.00000000 73.00000000 137.00000000 90.00000000
  104.00000000]
 [26.00000000 76.00000000 237.00000000 296.00000000 22.00000000
  83.00000000]
 [87.00000000 250.00000000 205.00000000 1

In [76]:
# среди первых шести строк вывод кажой пятой
print(my_data[:6:5,:])

[[0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
  0.00000000 0.00000000]
 [196.00000000 132.00000000 284.00000000 26.00000000 113.00000000
  148.00000000 119.00000000 261.00000000 252.00000000 72.00000000
  279.00000000 242.00000000 29.00000000 64.00000000 179.00000000
  280.00000000 78.00000000 199.00000000 8.00000000 105.00000000
  287.00000000 58.00000000 286.00000000 197.00000000 269.00000000
  31.00000000 243.00000000 45.00000000 220.00000000 235.00000000
  153.00000000 119.00000000 95.00000000

In [77]:
# обнуление 1 строки
my_data[0] = 0
print(my_data)

[[0.00000000 0.00000000 0.00000000 ... 0.00000000 0.00000000 0.00000000]
 [139.00000000 93.00000000 64.00000000 ... 232.00000000 114.00000000
  147.00000000]
 [295.00000000 265.00000000 123.00000000 ... 89.00000000 13.00000000
  104.00000000]
 ...
 [96.00000000 69.00000000 180.00000000 ... 57.00000000 49.00000000
  55.00000000]
 [108.00000000 72.00000000 229.00000000 ... 65.00000000 102.00000000
  160.00000000]
 [93.00000000 133.00000000 39.00000000 ... 258.00000000 26.00000000
  175.00000000]]


In [78]:
# вывод суммы элемнтов
print(my_data.sum())

367654.0


In [79]:
# вывод среднего значения
print(my_data.mean())

147.0616


In [80]:
# вывод медианы
print(np.median(my_data))

146.0


In [81]:
# вывод стандартного отклонения
print(np.std(my_data))

87.21184441026344


In [82]:
# нормализация
print((my_data- np.min(my_data)) / (np.max(my_data) - np.min(my_data)))


[[0.00000000 0.00000000 0.00000000 ... 0.00000000 0.00000000 0.00000000]
 [0.46488294 0.31103679 0.21404682 ... 0.77591973 0.38127090 0.49163880]
 [0.98662207 0.88628763 0.41137124 ... 0.29765886 0.04347826 0.34782609]
 ...
 [0.32107023 0.23076923 0.60200669 ... 0.19063545 0.16387960 0.18394649]
 [0.36120401 0.24080268 0.76588629 ... 0.21739130 0.34113712 0.53511706]
 [0.31103679 0.44481605 0.13043478 ... 0.86287625 0.08695652 0.58528428]]


In [83]:
# стандартизация
np.set_printoptions(precision=8, suppress=True, formatter={'all': lambda x: f'{x:0.8f}'})
print((my_data- np.mean(my_data)) / (np.std(my_data)))

[[-1.68625719 -1.68625719 -1.68625719 ... -1.68625719 -1.68625719
  -1.68625719]
 [-0.09243699 -0.61988828 -0.95241192 ... 0.97393193 -0.37909530
  -0.00070633]
 [1.69631087 1.35232090 -0.27589830 ... -0.66575361 -1.53719487
  -0.49375862]
 ...
 [-0.58548928 -0.89508026 0.37768264 ... -1.03267624 -1.12440690
  -1.05560891]
 [-0.44789329 -0.86068126 0.93953293 ... -0.94094559 -0.51669129
  0.14835600]
 [-0.61988828 -0.16123498 -1.23907023 ... 1.27205657 -1.38813255
  0.32035098]]
